
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MOJ.ProductManagement.WebApi.Enums
{
    public static partial class LookupEnums
    {
        public enum QuantityPerUnit
        {
            Bottle = 14,
            Box = 11,
            Can = 12,
            Kilo = 10,
            Liter = 13
        }

        public static class QuantityPerUnitGroup
        {
            public const int Bottle = 14;
            public const int Box = 11;
            public const int Can = 12;
            public const int Kilo = 10;
            public const int Liter = 13;
        }

    }
}

